In [2]:
from datetime import datetime

import corner
import emcee
import matplotlib as plt
import numpy as np

import itm.likelihood
import itm.utils
from itm.posterior_calculator import PosteriorCalculator
 
config_params = itm.utils.load_config("/Users/fabio/code/fchibana/tachyons/config.yaml")

print(config_params)

mcmc_params = config_params["mcmc_params"]


p0 = [24.96, 0.69, 0.022, 0.12]         # initial guess 
ndim = len(p0)  
nwalkers =  mcmc_params["n_walkers"] 

out_name = "results/" + datetime.now().strftime("%Y%m%d_%H%M%S")
print(out_name)

backend = emcee.backends.HDFBackend(out_name + ".h5")
backend.reset(nwalkers, ndim)


# # MCMC =============================================================================================

print("MCMC")
print("walkers: ", nwalkers)



# # initialize sampler
# sampler = emcee.EnsembleSampler(nwalkers, ndim, itm.likelihood.lnprob, backend=backend)

prob = PosteriorCalculator()
sampler = emcee.EnsembleSampler(nwalkers, ndim, prob.ln_posterior, backend=backend)

# # condicoes iniciais dos walkers dentro da bola de centro p1_0
pos = [p0 + 1e-4*np.random.randn(ndim) for i in range(nwalkers)]

max_n = 1000

# # We'll track how the average autocorrelation time estimate changes
index = 0
autocorr = np.empty(max_n)

# # This will be useful to testing convergence
old_tau = np.inf

# Now we'll sample for up to max_n steps
for sample in sampler.sample(pos, iterations=max_n, progress=True):
    # Only check convergence every 100 steps
    steps = sampler.iteration
    if sampler.iteration % 100:
        continue

    # Compute the autocorrelation time so far
    # Using tol=0 means that we'll always get an estimate even
    # if it isn't trustworthy
    tau = sampler.get_autocorr_time(tol=0)
    print(tau)
    autocorr[index] = np.mean(tau)
    index += 1

    # Check convergence
    converged = np.all(tau * 100 < sampler.iteration)
    converged &= np.all(np.abs(old_tau - tau) / tau < 0.01)
    if converged:
        break
    old_tau = tau
    


# # Analysis ===========================================================================================

# tau = sampler.get_autocorr_time()
# burnin = int(2 * np.max(tau))
# thin = int(0.5 * np.min(tau))
# flat_samples = sampler.get_chain(discard=burnin, flat=True, thin=thin)

flat_samples = sampler.get_chain(flat=True)
print(flat_samples.shape)

fig = corner.corner(flat_samples,
                    labels=["M", "$h$",
                            "$\Omega_{b} h^2$", "$\Omega_{c} h^2$"],
                    quantiles=(0.16, 0.5, 0.84), show_titles=True,
                    title_kwargs={"fontsize": 12})
fig.suptitle('walkers: %s steps: %s' % (nwalkers, steps))
fig = corner.corner(flat_samples)
# fig.show()

fig.savefig(out_name + ".png")


{'constants': {'c': 299792458.0}, 'cosmo_params': {'jla_norm': 25.0}, 'mcmc_params': {'n_walkers': 32}}
results/20220319_153137
MCMC
walkers:  32


 11%|█         | 107/1000 [00:02<00:20, 43.15it/s]

[9.88715439 9.76540195 9.49773862 9.13380555]


 21%|██        | 206/1000 [00:05<00:19, 39.77it/s]

[18.07951454 18.30343893 17.35405573 15.67589776]


 31%|███       | 307/1000 [00:08<00:18, 36.94it/s]

[14.14421268 25.7184732  24.60218974 25.90037049]


KeyboardInterrupt: 