In [1]:
import pandas as pd
import numpy as np

In [ ]:
params = [24.96, 0.69, 0.022, 0.12] 

In [ ]:
from itm.lcdm import H

In [ ]:
data.info

<bound method DataFrame.info of          z   H(z)    err
0   0.0708   69.0  19.68
1   0.0900   69.0  15.00
2   0.1200   68.6  26.20
3   0.1700   83.0   8.00
4   0.1790   75.0   4.00
5   0.1990   75.0   5.00
6   0.2000   72.9  29.60
7   0.2700   77.0  14.00
8   0.2800   88.8  36.60
9   0.3500   82.1   4.85
10  0.3520   83.0  14.00
11  0.4000   95.0  17.00
12  0.4004   77.0  10.20
13  0.4247   87.1  11.20
14  0.4497   92.8  12.90
15  0.4783   80.9   9.00
16  0.4800   97.0  62.00
17  0.5929  104.0  13.00
18  0.6797   92.0   8.00
19  0.7812  105.0  12.00
20  0.8754  125.0  17.00
21  0.8800   90.0  40.00
22  0.9000  117.0  23.00
23  1.0370  154.0  20.00
24  1.3000  168.0  17.00
25  1.3630  160.0  33.60
26  1.4300  177.0  18.00
27  1.5300  140.0  14.00
28  1.7500  202.0  40.00
29  1.9650  186.5  50.40>

In [ ]:
data = pd.read_csv("data/hubble.csv")

x = data["z"].to_numpy()
y = data["H"].to_numpy()
y_err = data["err"].to_numpy()

model = H(x, params)

In [ ]:
def ln_likelihood(y_fit, y_target, y_err):
    inv_sigma2 = 1.0 / y_err**2
    return -0.5 * (np.sum((y_target - y_fit)**2 * inv_sigma2 - np.log(inv_sigma2)))
    

In [ ]:
ln_likelihood(model, y, y_err)

-90.90551637968684

In [ ]:
lnlikehood

-90.90551637968684

In [ ]:
        # initial guess
model = H(df["z"], params)
model.to_numpy()
# inv_sigma2 = 1.0/yerr**2

# lnlikehood += -0.5 * \
# (np.sum((y-model)**2*inv_sigma2 - np.log(inv_sigma2)))

array([ 71.30598591,  71.97251533,  73.04888493,  74.93668374,
        75.28883965,  76.08478496,  76.12506485,  79.05757329,
        79.49448017,  82.67591308,  82.76993535,  85.07751008,
        85.09714803,  86.30264571,  87.56829358,  89.04736793,
        89.13632167,  95.29731446, 100.36051172, 106.62034323,
       112.73932448, 113.04546069, 114.38424504, 123.8839227 ,
       143.6134155 , 148.60880392, 154.0286447 , 162.31684513,
       181.34623933, 200.93172944])

In [ ]:
from itm.likelihood_v2 import Prob


In [ ]:
probs = Prob()

In [ ]:
params = [24.96, 0.69, 0.022, 0.12] 
probs.ln_likelihood(params)

0

In [ ]:
# Test: select experiments

experiments = ['local_hubble', 'cosmic_chronometers']

In [ ]:
'local_hubble' in experiments

True

In [ ]:
from itm.posterior_calculator import PosteriorCalculator

posterior = PosteriorCalculator(experiments)
posterior._hubble_constant

Loading local_hubble data


{'y': 73.02, 'y_err': 1.79}

Test distance modulus

In [3]:
from itm.lcdm import LCDM
from itm.observables import Observables
import numpy as np

cosmology = LCDM()
observable_test = Observables(cosmology)

In [4]:
z = np.linspace(0.1, 3, 10)
params = [24.96, 0.69, 0.022, 0.12]
observable_test._inv_E(z, params)

array([0.95400607, 0.80066276, 0.66147368, 0.54755781, 0.45789338,
       0.38784582, 0.33277099, 0.28894944, 0.25360614, 0.22471391])

In [5]:
observable_test._comoving_distance(z, params)

array([ 424.57204769, 1652.58282049, 2673.39290805, 3516.68063739,
       4217.91467595, 4807.92949992, 5310.85212001, 5744.92281335,
       6123.85372042, 6458.02054696])

In [5]:
observable_test.distance_modulus(z, params)

array([38.30672042, 41.81565347, 43.30359967, 44.26701683, 44.9764687 ,
       45.53552704, 45.99542173, 46.38524316, 46.72305146, 47.02079707])

Convert covariance matrix from list to np.array

In [6]:
x, y = np.loadtxt("data/jla_mub.txt", comments='#', unpack=True)
flatten_cov = np.loadtxt("data/jla_mub_covmatrix.dat")

In [7]:
cov = flatten_cov.reshape((x.shape[0], x.shape[0]))
inv_cov = np.linalg.inv(cov)
det_inv_cov = np.linalg.det(inv_cov)

print(cov.shape)
print(inv_cov.shape)
print(det_inv_cov)

(31, 31)
(31, 31)
1.4884660039785232e+78


In [6]:
# model = []
# for i in range(len(x)):
#     model.append(distance_modulus(x[i], params))
model = observable_test.distance_modulus(x, params)
r = y - model

chi2 = np.dot(r, np.dot(inv_cov, r))

lnlikehood = -0.5 * (chi2 - np.log(det_inv_cov))

print(r)
print(chi2)
print(lnlikehood)

NameError: name 'x' is not defined

In [25]:
# convert flat values to matrix form
# import the flattened covariance values
aux = np.loadtxt("data/jla_mub_covmatrix.dat")
# dimension of the matrix
ndim = int(np.sqrt(len(aux)))
# initilize the matrix
cov_mat = np.zeros((ndim, ndim))
i = 0
for j in range(ndim):
    for k in range(ndim):
        cov_mat[j][k] = aux[i]
        i = i+1
inv_cov_mat = np.linalg.inv(cov_mat)
inv_det_C = np.linalg.det(inv_cov_mat)
print(inv_det_C)

1.4884660039785232e+78


In [18]:
np.count_nonzero(cov == cov_mat)

961

In [7]:
x, y, _ = np.loadtxt("data/bao.txt", comments='#', unpack=True )

model = observable_test.d_BAO(x, params)
# for i in range(len(x)):
#     model.append(d_BAO(x[i], params))

print("\nTest BAO:")
print("Data    Model   Diff")
for i in range(len(y)):
    msg = "{0:.3f}    {1:.3f}    {2:.3f}".format(y[i], model[i], abs((y[i]-model[i])/model[i]))
    print(msg)


Test BAO:
Data    Model   Diff
2.980    2.962    0.006
4.350    4.132    0.053
8.250    8.309    0.007
13.420    13.494    0.005
